valid_protocols <-
  c(
    "Area",
    "Audubon Coastal Bird Survey",
    "Banding",
    "BirdLife Australia 20min-2ha survey",
    "BirdLife Australia 5 km radius search",
    "BirdLife Australia 500m radius search",
    "Birds 'n' Bogs Survey",
    "Breeding Bird Atlas",
    "CAC--Common Bird Survey",
    "California Brown Pelican Survey",
    "Caribbean Martin Survey",
    "Coastal Shorebird Survey",
    "CWC Area Search",
    "CWC Point Count",
    "CWC Traveling Count",
    "eBird Pelagic Protocol",
    "Great Texas Birding Classic",
    "Greater Gulf Refuge Waterbird Count",
    "Heron Area Count",
    "Heron Stationary Count",
    "Historical",
    "IBA Canada (protocol)",
    "Incidental",
    "International Shorebird Survey (ISS)",
    "LoonWatch",
    "My Yard Counts",
    "Nocturnal Flight Call Count",
    "Oiled Birds",
    "PROALAS",
    "RAM--Iberian Seawatch Network",
    "Random",
    "Rusty Blackbird Spring Migration Blitz",
    "Standardized Yard Count",
    "Stationary",
    "TNC California Waterbird Count",
    "Trail Tracker",
    "Traveling",
    "Traveling - Property Specific",
    "Tricolored Blackbird Winter Survey",
    "Waterbird Count",
    "Yellow-billed Magpie Survey - General Observations",
    "Yellow-billed Magpie Survey - Traveling Count"
  )
usethis::use_data(valid_protocols)